name: CI

on:
  pull_request:
  push:
      branches:
        - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - run: |
          find . -name "*.s" | xargs -I {} nasm -Xgnu -I. -o/dev/null {}